import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Header } from "@/components/header";

const luminaire = localFont({
  src: "../fonts/Luminaire.otf",
  variable: "--font-luminaire",
  display: "swap",
});

const marlton = localFont({
  src: "../fonts/MarltonSans.otf",
  variable: "--font-marlton",
  display: "swap",
});

const satoshi = localFont({
  src: "../fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${luminaire.variable} ${marlton.variable} ${satoshi.variable} min-h-svh flex flex-col items-center justify-center w-full h-full`}
      >
        <Header />
        <main className="flex-1 w-full">{children}</main>
      </body>
    </html>
  );
}
