import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { Header } from "@/components/header";
import { OsDetection } from "./os-detection";
import { Footer } from "@/components/footer";
import { Popup } from "@/components/modals/popup";
import { QuoteModalProvider } from "@/hooks/use-quote-modal";
import { QuoteModal } from "@/components/modals/quote-modal";

const luminaire = localFont({
  src: "../fonts/Luminaire.otf",
  variable: "--font-luminaire",
  display: "swap",
});

const marlton = localFont({
  src: "../fonts/MarltonSans.otf",
  variable: "--font-marlton",
  display: "swap",
});

const satoshi = localFont({
  src: "../fonts/Satoshi-Variable.woff2",
  variable: "--font-satoshi",
  display: "swap",
  weight: "200 300 400 500 600 700 800 900",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${luminaire.variable} overflow-x-clip ${marlton.variable} ${satoshi.variable} ${inter.variable} min-h-svh flex flex-col items-center justify-center max-w-screen w-full h-full`}
      >
        <QuoteModalProvider>
          <OsDetection />
          <Header />
          <main className="flex-1 w-full">{children}</main>
          <Footer />
          <Popup />
          <QuoteModal />
        </QuoteModalProvider>
      </body>
    </html>
  );
}
